version: '3.4'

services:
  # app : server
  server:
    container_name: server
    build:
      context: ..
      dockerfile: ./devops/local/apps/Dockerfile
      args:
        - BUILD_CONTEXT=server
    volumes:
      - '../code/libs:/src/code/libs'
      - '../code/apps/server:/src/code/apps/server'
    restart: always
    labels:
      - 'traefik.http.routers.server.rule=Host(`server.localhost`)'
  # app : admin-dashboard
  admin-dashboard:
    container_name: admin-dashboard
    build:
      context: ..
      dockerfile: ./devops/local/apps/Dockerfile
      args:
        - BUILD_CONTEXT=admin-dashboard
    volumes:
      - '../code/libs:/src/code/libs'
      - '../code/apps/admin-dashboard:/src/code/apps/admin-dashboard'
    restart: always
    labels:
      - 'traefik.http.routers.admin.rule=Host(`admin.localhost`)'
  # app : client
  client:
    container_name: client
    build:
      context: ..
      dockerfile: ./devops/local/apps/Dockerfile
      args:
        - BUILD_CONTEXT=client
    volumes:
      - '../code/libs:/src/code/libs'
      - '../code/apps/client:/src/code/apps/client'
    restart: always
