version: '3.4'

services:
  # app : server
  server:
    container_name: server
    security_opt:
      - no-new-privileges:true
    build:
      context: ..
      dockerfile: ./devops/local/apps/Dockerfile
      args:
        - BUILD_CONTEXT=server
    volumes:
      - '../code/libs:/src/code/libs'
      - '../code/apps/server:/src/code/apps/server'
    restart: always
    labels:
      - 'traefik.http.routers.server.rule=Host(`server.foxmono.localhost`)'
      - 'traefik.enable=true'
      - 'traefik.http.routers.server.tls=true'
    networks:
      - proxy
  # app : admin-dashboard
  admin-dashboard:
    container_name: admin-dashboard
    security_opt:
      - no-new-privileges:true
    build:
      context: ..
      dockerfile: ./devops/local/apps/Dockerfile
      args:
        - BUILD_CONTEXT=admin-dashboard
    volumes:
      - '../code/libs:/src/code/libs'
      - '../code/apps/admin-dashboard:/src/code/apps/admin-dashboard'
    restart: always
    labels:
      - 'traefik.http.routers.admin.rule=Host(`admin.foxmono.localhost`)'
      - 'traefik.enable=true'
      - 'traefik.http.routers.admin.tls=true'
    networks:
      - proxy
  # app : client
  client:
    container_name: client
    build:
      context: ..
      dockerfile: ./devops/local/apps/Dockerfile
      args:
        - BUILD_CONTEXT=client
    volumes:
      - '../code/libs:/src/code/libs'
      - '../code/apps/client:/src/code/apps/client'
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
