version: '3.4'

services:
  # reverse proxy
  reverse-proxy:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # command: --api.insecure=true --providers.docker
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik=true'
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      - proxy
  whoami:
    image: traefik/whoami
    scale: 2
    security_opt:
      - no-new-privileges:true
    labels:
      - 'traefik.http.routers.whoami.rule=Host(`whoami.foxmono.localhost`)'
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.tls=true'
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
